// Regenerates public/vendor/three/three.min.js: a minified subset of Three.js.
// Development-time only; the runtime site still has no npm dependency.
// node scripts/vendor-three.mjs   (needs network access for npm pack / npx esbuild)
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const version = "0.186.1";
// Keep in sync with the imports in public/scene/*.mjs.
const exportsList = [
  "AdditiveBlending", "BufferAttribute", "BufferGeometry", "Color", "Group",
  "IcosahedronGeometry", "LineBasicMaterial", "LineSegments", "Mesh",
  "PerspectiveCamera", "Points", "Scene", "ShaderMaterial",
  "Vector3", "WebGLRenderer",
];

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "public", "vendor", "three");
const work = await mkdtemp(join(tmpdir(), "vendor-three-"));
const shell = process.platform === "win32";

try {
  execFileSync("npm", ["pack", `three@${version}`, "--silent"], { cwd: work, shell, stdio: "inherit" });
  execFileSync("tar", ["-xzf", `three-${version}.tgz`], { cwd: work, stdio: "inherit" });
  const entry = join(work, "entry.mjs");
  await writeFile(entry, `export { ${exportsList.join(", ")} } from "./package/build/three.module.js";\n`);
  const output = join(target, "three.min.js");
  execFileSync("npx", ["--yes", "esbuild@0.25.10", entry, "--bundle", "--minify", "--format=esm", "--legal-comments=inline", `--outfile=${output}`], { cwd: work, shell, stdio: "inherit" });
  await copyFile(join(work, "package", "LICENSE"), join(target, "LICENSE"));

  const bundle = await readFile(output);
  const sha256 = createHash("sha256").update(bundle).digest("hex");
  await writeFile(join(target, "VERSION.md"), [
    "# Three.js subset",
    "",
    `- Source: npm \`three@${version}\` (https://github.com/mrdoob/three.js), MIT License (see LICENSE).`,
    "- Generated by `node scripts/vendor-three.mjs`; do not edit three.min.js by hand.",
    `- Exports: ${exportsList.join(", ")}.`,
    `- Size: ${bundle.length} bytes, ${gzipSync(bundle, { level: 9 }).length} bytes gzip.`,
    `- SHA-256: \`${sha256}\``,
    "",
  ].join("\n"));
  console.log(`three.min.js ${bundle.length} bytes, sha256 ${sha256}`);
} finally {
  await rm(work, { recursive: true, force: true });
}
